
class movimento:
    def mover (vel_roda_esq, vel_roda_dir):
        ...
        print (f"vel esq: {vel_roda_esq}; vel dir: {vel_roda_dir}")
        ...
    
    def girar (angulo):
        ...

    def andar (tanto):
        ...